random_seed = 0

[input]
size = 8

[[layers]]
kind = "regular_feedforward"
size = 3
activation = "sigmoid"

[layers.visualization]
weights = true

[[layers]]
kind = "regular_feedforward"
size = 8
activation = "sigmoid"

[layers.visualization]
weights = true

[cost]
function = "mean_square_error"

[accuracy]
function = "rounded_equal"

[optimizer]
function = "Adam"

[optimizer.parameters]
epsilon = 1e-3
# learning_rate = 0.04

[optimizer.parameters.learning_rate]
function = "exponential_decay"

[optimizer.parameters.learning_rate.parameters]
initial_rate = 0.05
to = 0.0001
decay_steps = 10000
staircase = false

[initial_weights]
function = "truncated_normal"

[initial_weights.parameters]
stddev = 0.1

[data]
case_fraction = 1.0

[data.source]
function = "import_dataset"

[data.source.parameters]
filepath = "dataset.py"
dataset = "autoencode"

[validation]
fraction = 0.1
interval = 10

[test]
fraction = 0.1

[minibatch]
size = 100
steps = 1000

[visualization]
size = 8
dendogram_layers = [0, 1, 2]