[dimensions.layers]
num = 2
size = 32

[dimensions.input]
size = 784

[dimensions.output]
size = 10

[activation.layers]
function = "sigmoid"

[activation.output]
function = "softmax"

[cost]
function = "mean_square_error"

[optimizer]
function = "Adam"

[optimizer.parameters]
epsilon = 1e-4

[optimizer.parameters.learning_rate]
function = "exponential_decay"

[optimizer.parameters.learning_rate.parameters]
initial_rate = 0.06
decay_steps = 10000
decay_rate = 0.98
staircase = false

[initial_weights]
lower = -4
upper = 4

[data]
case_fraction = 0.1

[data.source]
function = "import_dataset"

[data.source.parameters]
filepath = "dataset.py"
dataset = "mnist"

[validation]
fraction = 0.1
interval = 100

[test]
fraction = 0.1

[minibatch]
size = 100
steps = 5000

[visualization]
weights = [1, 2, 3, 4]
biasses = [1, 4]

[visualization.map]
size = 0
layers = [0, 5]
dendogram_layers = [5]
